// Copyright (c) 2026 OpenWALDO Project contributors
// Copyright (c) 2026 CtrlIQ, Inc.
// Copyright (c) 2026 Gregory M. Kurtzer
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strings"
	"unicode/utf8"

	"github.com/charmbracelet/glamour"
	"golang.org/x/term"
)

var terminalOutputWidth = func() int {
	width, _, err := term.GetSize(int(os.Stdout.Fd()))
	if err != nil || width < 60 {
		return 88
	}
	if width > 120 {
		return 120
	}
	return width
}

var terminalMarkdownLive = func(output io.Writer) bool {
	file, ok := output.(*os.File)
	return ok && term.IsTerminal(int(file.Fd()))
}

func renderedTerminalMarkdown(markdown string) (string, error) {
	renderer, err := glamour.NewTermRenderer(glamour.WithAutoStyle(), glamour.WithWordWrap(terminalOutputWidth()))
	if err != nil {
		return "", fmt.Errorf("initialize terminal Markdown renderer: %w", err)
	}
	rendered, err := renderer.Render(strings.TrimSpace(markdown) + "\n")
	if err != nil {
		return "", fmt.Errorf("render Markdown: %w", err)
	}
	return rendered, nil
}

func renderTerminalMarkdown(output io.Writer, markdown string) error {
	rendered, err := renderedTerminalMarkdown(markdown)
	if err != nil {
		return err
	}
	_, err = fmt.Fprint(output, rendered)
	return err
}

// liveMarkdownOutput periodically replaces its terminal preview with a fresh
// rendering of all Markdown received so far. Re-rendering preserves constructs
// whose meaning changes as more text arrives, such as lists and fenced code.
// Non-terminal output is rendered once at completion and never receives ANSI
// cursor controls.
type liveMarkdownOutput struct {
	output        io.Writer
	markdown      bytes.Buffer
	live          bool
	nextRefresh   int
	renderedLines int
	renderedInput string
}

func newLiveMarkdownOutput(output io.Writer) *liveMarkdownOutput {
	return &liveMarkdownOutput{output: output, live: terminalMarkdownLive(output), nextRefresh: 64}
}

func (output *liveMarkdownOutput) Write(value []byte) (int, error) {
	written, err := output.markdown.Write(value)
	if err != nil || !output.live {
		return written, err
	}
	if output.markdown.Len() >= output.nextRefresh || bytes.Contains(value, []byte{'\n'}) {
		if err := output.refresh(false); err != nil {
			return written, err
		}
	}
	return written, nil
}

func (output *liveMarkdownOutput) Finish() error {
	return output.refresh(true)
}

func (output *liveMarkdownOutput) refresh(force bool) error {
	markdown := output.markdown.String()
	if strings.TrimSpace(markdown) == "" || markdown == output.renderedInput {
		return nil
	}
	if !output.live && !force {
		return nil
	}
	rendered, err := renderedTerminalMarkdown(markdown)
	if err != nil {
		return err
	}
	if output.renderedLines > 0 {
		if _, err := fmt.Fprintf(output.output, "\x1b[%dA\r\x1b[J", output.renderedLines); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(output.output, rendered); err != nil {
		return err
	}
	output.renderedLines = max(1, strings.Count(rendered, "\n"))
	output.renderedInput = markdown
	output.nextRefresh = output.markdown.Len() + 64
	return nil
}

// safeTokenWriter streams generated byte tokens without allowing terminal
// control sequences. Newline and tab remain readable; other controls and
// invalid UTF-8 bytes are rendered as hexadecimal escapes.
type safeTokenWriter struct {
	writer         io.Writer
	pending        []byte
	carriageReturn bool
}

func (renderer *safeTokenWriter) Write(data []byte) error {
	renderer.pending = append(renderer.pending, data...)
	for len(renderer.pending) > 0 {
		if renderer.carriageReturn {
			if renderer.pending[0] == '\n' {
				if _, err := renderer.writer.Write([]byte{'\n'}); err != nil {
					return err
				}
				renderer.pending = renderer.pending[1:]
				renderer.carriageReturn = false
				continue
			}
			if _, err := io.WriteString(renderer.writer, "\\x0d"); err != nil {
				return err
			}
			renderer.carriageReturn = false
		}
		first := renderer.pending[0]
		if first < utf8.RuneSelf {
			renderer.pending = renderer.pending[1:]
			if first == '\r' {
				renderer.carriageReturn = true
			} else if first == '\n' || first == '\t' || first >= 0x20 && first != 0x7f {
				if _, err := renderer.writer.Write([]byte{first}); err != nil {
					return err
				}
			} else if _, err := fmt.Fprintf(renderer.writer, "\\x%02x", first); err != nil {
				return err
			}
			continue
		}
		if !utf8.FullRune(renderer.pending) {
			return nil
		}
		runeValue, size := utf8.DecodeRune(renderer.pending)
		if runeValue == utf8.RuneError && size == 1 {
			if _, err := fmt.Fprintf(renderer.writer, "\\x%02x", first); err != nil {
				return err
			}
			renderer.pending = renderer.pending[1:]
			continue
		}
		if _, err := renderer.writer.Write(renderer.pending[:size]); err != nil {
			return err
		}
		renderer.pending = renderer.pending[size:]
	}
	return nil
}

func (renderer *safeTokenWriter) Flush() error {
	if renderer.carriageReturn {
		if _, err := io.WriteString(renderer.writer, "\\x0d"); err != nil {
			return err
		}
		renderer.carriageReturn = false
	}
	for _, value := range renderer.pending {
		if _, err := fmt.Fprintf(renderer.writer, "\\x%02x", value); err != nil {
			return err
		}
	}
	renderer.pending = nil
	return nil
}
